---
address: 172.31.186.156:50050
username: shdu
password: password
tls_ca: ca-chain.cert.pem
tls_cert: user_shdu_chain.cert.pem
tls_key: user_shdu.key.unenc.pem
encoding: PROTO
get: /interfaces/interface[name=eth1/1]/state/counters
set:
  path: /System
  file: ./config/int_desc_update.json
replace:
  path: /System/bgp-items
  file: ./config/bgp_items.json
  #path: /System
  #file: ./config/system.json
subscriptions:
  - path: /interfaces/interface/state/oper-status
    mode: ON_CHANGE
  #- path: /syslog/message
    #origin: Syslog-oper
    #mode: ON_CHANGE
